# Generated by Django 3.1.4 on 2020-12-18 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('wash', models.CharField(choices=[('R', 'Rinse in Sink'), ('S', 'Scrub in Tub'), ('D', 'Deep Soak')], default='R', max_length=1)),
                ('potato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.potato')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
